#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BUFFER_SIZE 2048
#define MIN_PRIME_BITS 512
#define AES_BLOCK_SIZE 16
#define AES_KEY_SIZE 16
#define AES_ROUNDS 10
#define MAX_ALGORITHMS 10

#endif // CONSTANTS_H