#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BUFFER_SIZE 1024
#define BUFFER_SIZE 1024
#define AES_KEY_SIZE 128
#define MIN_PRIME_BITS 512
#define AES_BLOCK_SIZE 16
#define AES_ROUNDS 10
#define AES_KEY_SIZE 128 // 1024 bits
#endif // CONSTANTS_H